apiVersion: v1
kind: Service
metadata:
  name: retail-app-service
  namespace: default 
spec: 
  type: NodePort
  selector:
    app: retail-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
